---
abstract: 'Add index and search methods to Apache::Session'
author:
  - 'LLNG Team <https://lemonldap-ng.org>'
build_requires:
  DBD::SQLite: '0'
  DBI: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4234, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Apache-Session-Browseable
provides:
  Apache::Session::Browseable:
    file: lib/Apache/Session/Browseable.pm
    version: v1.3.17
  Apache::Session::Browseable::Cassandra:
    file: lib/Apache/Session/Browseable/Cassandra.pm
    version: v1.3.13
  Apache::Session::Browseable::DBI:
    file: lib/Apache/Session/Browseable/DBI.pm
    version: v1.3.9
  Apache::Session::Browseable::File:
    file: lib/Apache/Session/Browseable/File.pm
    version: v1.3.5
  Apache::Session::Browseable::Informix:
    file: lib/Apache/Session/Browseable/Informix.pm
    version: v1.2.2
  Apache::Session::Browseable::LDAP:
    file: lib/Apache/Session/Browseable/LDAP.pm
    version: v1.3.6
  Apache::Session::Browseable::MySQL:
    file: lib/Apache/Session/Browseable/MySQL.pm
    version: v1.2.5
  Apache::Session::Browseable::MySQLJSON:
    file: lib/Apache/Session/Browseable/MySQLJSON.pm
    version: v1.3.9
  Apache::Session::Browseable::Oracle:
    file: lib/Apache/Session/Browseable/Oracle.pm
    version: v1.2.2
  Apache::Session::Browseable::Patroni:
    file: lib/Apache/Session/Browseable/Patroni.pm
    version: v1.3.17
  Apache::Session::Browseable::PgHstore:
    file: lib/Apache/Session/Browseable/PgHstore.pm
    version: v1.3.9
  Apache::Session::Browseable::PgJSON:
    file: lib/Apache/Session/Browseable/PgJSON.pm
    version: v1.3.9
  Apache::Session::Browseable::Postgres:
    file: lib/Apache/Session/Browseable/Postgres.pm
    version: v1.3.1
  Apache::Session::Browseable::Redis:
    file: lib/Apache/Session/Browseable/Redis.pm
    version: v1.3.16
  Apache::Session::Browseable::SQLite:
    file: lib/Apache/Session/Browseable/SQLite.pm
    version: v1.2.2
  Apache::Session::Browseable::Store::Cassandra:
    file: lib/Apache/Session/Browseable/Store/Cassandra.pm
    version: v1.3.13
  Apache::Session::Browseable::Store::DBI:
    file: lib/Apache/Session/Browseable/Store/DBI.pm
    version: v1.3.11
  Apache::Session::Browseable::Store::File:
    file: lib/Apache/Session/Browseable/Store/File.pm
    version: v1.2.2
  Apache::Session::Browseable::Store::Informix:
    file: lib/Apache/Session/Browseable/Store/Informix.pm
    version: v1.2.2
  Apache::Session::Browseable::Store::LDAP:
    file: lib/Apache/Session/Browseable/Store/LDAP.pm
    version: v1.3.8
  Apache::Session::Browseable::Store::MySQL:
    file: lib/Apache/Session/Browseable/Store/MySQL.pm
    version: v1.2.2
  Apache::Session::Browseable::Store::Oracle:
    file: lib/Apache/Session/Browseable/Store/Oracle.pm
    version: v1.2.2
  Apache::Session::Browseable::Store::Patroni:
    file: lib/Apache/Session/Browseable/Store/Patroni.pm
    version: v1.3.17
  Apache::Session::Browseable::Store::Postgres:
    file: lib/Apache/Session/Browseable/Store/Postgres.pm
    version: v1.2.2
  Apache::Session::Browseable::Store::Redis:
    file: lib/Apache/Session/Browseable/Store/Redis.pm
    version: v1.3.15
  Apache::Session::Browseable::Store::SQLite:
    file: lib/Apache/Session/Browseable/Store/SQLite.pm
    version: v1.2.7
  Apache::Session::Browseable::Store::Sybase:
    file: lib/Apache/Session/Browseable/Store/Sybase.pm
    version: v1.2.2
  Apache::Session::Browseable::Sybase:
    file: lib/Apache/Session/Browseable/Sybase.pm
    version: v1.2.2
  Apache::Session::Generate::SHA256:
    file: lib/Apache/Session/Generate/SHA256.pm
    version: v1.2.2
  Apache::Session::Serialize::Hstore:
    file: lib/Apache/Session/Serialize/Hstore.pm
    version: v1.2.5
  Apache::Session::Serialize::JSON:
    file: lib/Apache/Session/Serialize/JSON.pm
    version: v1.2.6
recommends:
  DBD::Cassandra: '0'
  DBI: '0'
  Net::LDAP: '0.38'
  Redis::Fast: '0'
requires:
  Apache::Session: '0'
  JSON: '0'
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/LemonLDAPNG/Apache-Session-Browseable
version: v1.3.17
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
