name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      postgres:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: sessions
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: sessions
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h 127.0.0.1 -proot"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
      mariadb:
        image: mariadb:11.8
        env:
          MARIADB_ROOT_PASSWORD: root
          MARIADB_DATABASE: sessions
        ports:
          - 3307:3306
        options: >-
          --health-cmd "healthcheck.sh --connect --innodb_initialized"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
      mariadb1011:
        image: mariadb:10.11
        env:
          MARIADB_ROOT_PASSWORD: root
          MARIADB_DATABASE: sessions
        ports:
          - 3308:3306
        options: >-
          --health-cmd "healthcheck.sh --connect --innodb_initialized"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
    steps:
      - uses: actions/checkout@v4
      - name: Install Perl dependencies
        run: sudo apt-get update && sudo apt-get install -y libmodule-build-perl libapache-session-perl libjson-perl libdbi-perl libdbd-sqlite3-perl libnet-ldap-perl libredis-perl libdbd-mysql-perl libdbd-pg-perl liblwp-protocol-psgi-perl libmariadb-dev libssl-dev cpanminus build-essential && sudo cpanm --notest DBD::MariaDB
      - name: Build and run tests
        env:
          REDIS_URL: localhost:6379
          PG_DSN: dbi:Pg:dbname=sessions;host=127.0.0.1;port=5432
          PG_USER: postgres
          PG_PASSWORD: postgres
          MYSQL_DSN: dbi:mysql:database=sessions;host=127.0.0.1;port=3306
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MARIADB_DSN: dbi:MariaDB:database=sessions;host=127.0.0.1;port=3307
          MARIADB_USER: root
          MARIADB_PASSWORD: root
        run: |
          perl Build.PL
          ./Build
          ./Build test
      - name: Run MariaDB tests with other MariaDB versions/drivers
        env:
          MARIADB_USER: root
          MARIADB_PASSWORD: root
        run: |
          MARIADB_DSN='dbi:MariaDB:database=sessions;host=127.0.0.1;port=3308' prove -b t/Apache-Session-Browseable-MariaDBJSON.t
          MARIADB_DSN='dbi:mysql:database=sessions;host=127.0.0.1;port=3308' prove -b t/Apache-Session-Browseable-MariaDBJSON.t
          MARIADB_DSN='dbi:mysql:database=sessions;host=127.0.0.1;port=3307' prove -b t/Apache-Session-Browseable-MariaDBJSON.t
